[package]
name = "schist-plugin-api"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
log.workspace = true
schist-core.workspace = true
schist-color.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
parking_lot.workspace = true
smallvec.workspace = true
rustc-hash.workspace = true
thiserror.workspace = true
