[package]
name = "schist-codecs-common"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
schist-core.workspace = true
schist-plugin-api.workspace = true
schist-codec-affinity.workspace = true
anyhow.workspace = true
log.workspace = true
image.workspace = true
libloading.workspace = true
sha2 = "0.10"
schist-color.workspace = true
schist-colormgmt.workspace = true
schist-compositor.workspace = true

[dev-dependencies]
crc32fast.workspace = true
moxcms = "0.8"
