//! Bundles the cross-built plug-in helpers into the library, when there
//! are any to bundle.
//!
//! A helper is a binary for an architecture other than the one being
//! compiled, so cargo cannot produce one as part of this build — the
//! root `Makefile` cross-compiles them first and points
//! `SCHIST_BUNDLED_HELPERS` at the directory they landed in. Unset or
//! empty, nothing is embedded and the host falls back to looking beside
//! the executable, which is what keeps a plain `cargo build` working
//! with no setup at all.
//!
//! This is an environment variable rather than a cargo feature on
//! purpose: a feature would make `cargo test --workspace` require
//! artifacts that only the Makefile knows how to produce.
//!
//! Each helper is deflated on the way in. They are built stripped, which
//! takes far more off than compression does, and what is left still
//! packs to about half — so two helpers cost a few hundred kilobytes of
//! binary rather than the best part of six megabytes.

use std::path::{Path, PathBuf};

fn main() {
    println!("cargo:rerun-if-env-changed=SCHIST_BUNDLED_HELPERS");

    let out = PathBuf::from(std::env::var_os("OUT_DIR").expect("cargo sets OUT_DIR"));
    let dir = std::env::var_os("SCHIST_BUNDLED_HELPERS")
        .map(PathBuf::from)
        .filter(|d| !d.as_os_str().is_empty());

    let helpers = match &dir {
        Some(d) => collect(d),
        None => Vec::new(),
    };

    let mut src = String::from(
        "// Generated by build.rs. Each helper this build carries, \
         deflated.\n",
    );
    // `#[used]` because the payload has to ship whether or not the
    // program ever reads it. Without it the optimiser is entirely within
    // its rights to notice that a binary which only ever asks for the
    // *names* never touches the bytes, fold the names into constants,
    // and drop several megabytes of helper on the floor -- which is
    // exactly what a thin-LTO release build was measured doing.
    src.push_str("#[used]\n");
    src.push_str("pub(crate) static BUNDLED: &[Helper] = &[\n");
    for (name, path) in &helpers {
        println!("cargo:rerun-if-changed={}", path.display());
        let raw = std::fs::read(path).unwrap_or_else(|e| panic!("reading {}: {e}", path.display()));

        // Level 9. This runs once per release build and the result is
        // read on someone else's machine, so the trade is entirely in
        // favour of the smaller output.
        let packed = miniz_oxide::deflate::compress_to_vec(&raw, 9);
        let packed_path = out.join(format!("{name}.deflate"));
        std::fs::write(&packed_path, &packed).expect("writing a packed helper");

        src.push_str(&format!(
            "    Helper {{ name: {:?}, size: {}, packed: include_bytes!({:?}) }},\n",
            name,
            raw.len(),
            packed_path.display().to_string()
        ));
    }
    src.push_str("];\n");

    // Names the exact set of bytes this build carries, so an upgraded
    // Schist unpacks into a directory of its own rather than reusing --
    // or worse, half-overwriting -- the previous version's helpers.
    src.push_str(&format!(
        "pub(crate) const BUNDLE_ID: &str = {:?};\n",
        bundle_id(&helpers)
    ));

    std::fs::write(out.join("bundled.rs"), src).expect("writing the bundle table");
}

/// Every file in `dir` that is named like a helper, sorted so the
/// generated table and its hash do not depend on directory order.
fn collect(dir: &Path) -> Vec<(String, PathBuf)> {
    println!("cargo:rerun-if-changed={}", dir.display());
    let Ok(entries) = std::fs::read_dir(dir) else {
        println!(
            "cargo:warning=SCHIST_BUNDLED_HELPERS={} cannot be read; \
             no helpers bundled",
            dir.display()
        );
        return Vec::new();
    };
    let mut found: Vec<(String, PathBuf)> = entries
        .flatten()
        .filter(|e| e.path().is_file())
        .filter_map(|e| {
            let name = e.file_name().to_string_lossy().into_owned();
            name.starts_with("schist-8bf-helper-")
                .then(|| (name, e.path()))
        })
        .collect();
    found.sort();
    if found.is_empty() {
        println!(
            "cargo:warning=no schist-8bf-helper-* in {}; no helpers bundled",
            dir.display()
        );
    }
    found
}

/// FNV-1a over each helper's name and contents. Only needs to change
/// when the bytes do, which rules out a version string: two builds of
/// the same version with different helpers must not collide.
fn bundle_id(helpers: &[(String, PathBuf)]) -> String {
    let mut h: u64 = 0xcbf2_9ce4_8422_2325;
    let mut eat = |bytes: &[u8]| {
        for b in bytes {
            h ^= *b as u64;
            h = h.wrapping_mul(0x100_0000_01b3);
        }
    };
    for (name, path) in helpers {
        eat(name.as_bytes());
        match std::fs::read(path) {
            Ok(bytes) => eat(&bytes),
            Err(e) => panic!("cannot read helper {}: {e}", path.display()),
        }
    }
    format!("{h:016x}")
}
