[package]
name = "schist-text-engine"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
schist-core.workspace = true
schist-color.workspace = true
fontdue = "0.9"
fontdb = "0.24"
ttf-parser = "0.25"
log.workspace = true
serde.workspace = true

[dev-dependencies]
serde_json.workspace = true
