[package]
name = "schist-tools-retouch"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
schist-core.workspace = true
schist-color.workspace = true
schist-plugin-api.workspace = true
schist-neural.workspace = true
log.workspace = true
rayon.workspace = true
